SELECT 
V_DB_WMSPRD_ESTOQUE_TOTAL.BEREICH AS 'AREA',
 V_DB_WMSPRD_ESTOQUE_TOTAL.PLATZ AS 'ENDERECO',
  V_DB_WMSPRD_ESTOQUE_TOTAL.ID_ARTIKEL AS 'CD_PROD',
   V_DB_WMSPRD_ESTOQUE_TOTAL.BEZ_1 AS 'DESC PROD', 
	V_DB_WMSPRD_ESTOQUE_TOTAL.CODE_EAN AS 'EAN',
	 V_DB_WMSPRD_ESTOQUE_TOTAL.EINH_MNG AS 'UN_EST', 
	  V_DB_WMSPRD_ESTOQUE_TOTAL.STAT_QK  AS 'BLOQ',
	   V_DB_WMSPRD_ESTOQUE_TOTAL.MOVIMENTACAO  AS 'MOVIMENTACAO', V_DB_WMSPRD_ESTOQUE_TOTAL.CHARGE, V_DB_WMSPRD_ESTOQUE_TOTAL.NR_LE_1, V_DB_WMSPRD_ESTOQUE_TOTAL.TYP_LE_1, V_DB_WMSPRD_ESTOQUE_TOTAL.MNG_FREI, V_DB_WMSPRD_ESTOQUE_TOTAL.MNG_RES_AUF, V_DB_WMSPRD_ESTOQUE_TOTAL.MNG_ZUGANG, V_DB_WMSPRD_ESTOQUE_TOTAL.VALIDADE, V_DB_WMSPRD_ESTOQUE_TOTAL.TOTAL
FROM DBA.dbo.V_DB_WMSPRD_ESTOQUE_TOTAL V_DB_WMSPRD_ESTOQUE_TOTAL