SELECT 
  V_DB_WMSPRD_ESTOQUE_TOTAL.ID_ARTIKEL AS 'CD_PROD',
   V_DB_WMSPRD_ESTOQUE_TOTAL.BEZ_1 AS 'DESC PROD', 
	V_DB_WMSPRD_ESTOQUE_TOTAL.CODE_EAN AS 'EAN',
	 V_DB_WMSPRD_ESTOQUE_TOTAL.EINH_MNG AS 'UN_EST', 
	  	  sum(V_DB_WMSPRD_ESTOQUE_TOTAL.MNG_FREI)'TOTAL'
		   


FROM DBA.dbo.V_DB_WMSPRD_ESTOQUE_TOTAL V_DB_WMSPRD_ESTOQUE_TOTAL

WHERE 
	V_DB_WMSPRD_ESTOQUE_TOTAL.ID_ARTIKEL LIKE '%11712'

	AND V_DB_WMSPRD_ESTOQUE_TOTAL.STAT_QK NOT IN (90)

	AND V_DB_WMSPRD_ESTOQUE_TOTAL.MNG_FREI > 0

	group by V_DB_WMSPRD_ESTOQUE_TOTAL.ID_ARTIKEL, V_DB_WMSPRD_ESTOQUE_TOTAL.BEZ_1, V_DB_WMSPRD_ESTOQUE_TOTAL.CODE_EAN, V_DB_WMSPRD_ESTOQUE_TOTAL.EINH_MNG, V_DB_WMSPRD_ESTOQUE_TOTAL.MNG_FREI