SELECT 
QUANTEN.BEREICH ,
QUANTEN.PLATZ ,
QUANTEN.ID_ARTIKEL ,

ARTIKEL.BEZ_1 , 
ARTIKEL.CODE_EAN ,
ARTIKEL.EINH_MNG,
QUANTEN.STAT_QK,

CASE QUANTEN.KNZ_IN_BEW
    WHEN '1' THEN 'S'
     ELSE 'N'
    END AS MOVIMENTACAO,
    
QUANTEN.CHARGE, 
QUANTEN.NR_LE_1,
QUANTEN.TYP_LE_1,
QUANTEN.MNG_FREI,
QUANTEN.MNG_RES_AUF,
QUANTEN.MNG_ZUGANG,
to_char(QUANTEN.DATUM_VERFALL,'dd/mm/yyyy')  VALIDADE,
(QUANTEN.MNG_FREI + QUANTEN.MNG_RES_AUF) AS "TOTAL"

FROM AG_CORE.ARTIKEL, AG_CORE.QUANTEN 
WHERE ARTIKEL.ID_ARTIKEL = QUANTEN.ID_ARTIKEL
AND ARTIKEL.ID_KLIENT =QUANTEN.ID_KLIENT
AND QUANTEN.ID_KLIENT= '001'
AND STAT_QK IN ('00')