--SELECT NR_AUF,STAT FROM AUFTRAEGE WHERE NR_AUF IN('99')

SELECT NR_AUF as PEDIDO, STAT FROM AUFTRAEGE WHERE  STAT IN (10, 15, 25)

SELECT NR_AUF as PEDIDO, STAT FROM AUFTRAEGE WHERE  STAT IN (35)

SELECT NR_AUF as PEDIDO, STAT FROM AUFTRAEGE WHERE  STAT IN (54,55,74)

SELECT NR_AUF as PEDIDO, STAT FROM AUFTRAEGE WHERE  STAT IN (75)



--ROTEIRIZAÇÃO
SELECT * FROM AUFTRAEGE WHERE  STAT IN (10, 15, 25) --TESTE
SELECT COUNT (NR_AUF), SUM(WERT_NACHN) FROM AUFTRAEGE WHERE  STAT IN (10, 15, 25) AND ART_EING != 'MAN' --TOTAL
SELECT * FROM (SELECT DATUM_BESTELL FROM AUFTRAEGE WHERE  STAT IN (10, 15, 25) AND ART_EING != 'MAN' ORDER BY DATUM_BESTELL ASC) WHERE ROWNUM=1 --DT ULTIMO PED

--RESERVA
SELECT * FROM AUFTRAEGE WHERE  STAT IN (35) --TESTE
SELECT COUNT (NR_AUF), SUM(WERT_NACHN) FROM AUFTRAEGE WHERE  STAT IN (35) AND ART_EING != 'MAN' --TOTAL
SELECT * FROM (SELECT DATUM_BESTELL FROM AUFTRAEGE WHERE  STAT IN (35) AND ART_EING != 'MAN' ORDER BY DATUM_BESTELL ASC) WHERE ROWNUM=1 --DT ULTIMO PED

--SEPARAÇÃO
SELECT * FROM AUFTRAEGE WHERE  STAT IN (54,55,74) AND ART_EING != 'MAN' --TESTE 
SELECT COUNT (NR_AUF), SUM(WERT_NACHN) FROM AUFTRAEGE WHERE  STAT IN (54,55,74) AND ART_EING != 'MAN' --TOTAL
SELECT * FROM (SELECT DATUM_BESTELL FROM AUFTRAEGE WHERE  STAT IN (54,55,74) AND ART_EING != 'MAN' ORDER BY DATUM_BESTELL ASC) WHERE ROWNUM=1 --DT ULTIMO PED

--FATURAMENTO
SELECT * FROM AUFTRAEGE WHERE  STAT IN (75) AND HINW_ZUST IS NULL AND ART_EING != 'MAN' AND NR_AUF NOT IN ('940587','495','716','838','1301','1290', '1300','962358', '962359', '962366', '962368', '962369', '962355' ) --TESTE
SELECT COUNT (NR_AUF), SUM(WERT_NACHN) FROM AUFTRAEGE WHERE  STAT IN (75) AND HINW_ZUST IS NULL AND ART_EING != 'MAN' AND NR_AUF NOT IN ('940587') -- TOTAL
SELECT * FROM (SELECT DATUM_BESTELL FROM AUFTRAEGE WHERE  STAT IN (75)  AND HINW_ZUST IS NULL AND ART_EING != 'MAN' AND NR_AUF NOT IN ('940587') ORDER BY DATUM_BESTELL ASC ) WHERE ROWNUM=1 --DT ULTIMO PED

--EXPEDIÇÃO

SELECT NR_AUF FROM AUFTRAEGE WHERE  STAT IN (75) AND HINW_ZUST IS not NULL AND ART_EING != 'MAN' AND NR_AUF NOT IN ('940587') and DATUM_BESTELL > '01-11-2020' ORDER BY 1--CAPTURA O NUMERO DOS PEDIDOS
SELECT COUNT (NR_AUF), SUM(WERT_NACHN) FROM AUFTRAEGE WHERE  STAT IN (75) AND HINW_ZUST IS not NULL AND ART_EING != 'MAN' AND NR_AUF NOT IN ('940587') and DATUM_BESTELL > '01-11-2020'
SELECT * FROM (SELECT DATUM_BESTELL FROM AUFTRAEGE WHERE  STAT IN (75)  AND HINW_ZUST IS  not NULL AND ART_EING != 'MAN' AND NR_AUF NOT IN ('940587')  and DATUM_BESTELL > '01-11-2020' ORDER BY DATUM_BESTELL ASC ) WHERE ROWNUM=1 --DT ULTIMO PED


SELECT  * FROM AUFTRAEGE WHERE  STAT IN (75) AND HINW_ZUST IS NULL AND ART_EING != 'MAN' AND NR_AUF NOT IN ('940587') -- TOTAL


describe AUFTRAEGE


--ENTREGA

SELECT NR_AUF FROM AUFTRAEGE WHERE  STAT IN (75) AND HINW_ZUST IS not NULL AND ART_EING != 'MAN' AND NR_AUF NOT IN ('940587') and DATUM_BESTELL > '01-11-2020' ORDER BY 1--CAPTURA O NUMERO DOS PEDIDOS
SELECT COUNT (NR_AUF), SUM(WERT_NACHN) FROM AUFTRAEGE WHERE  STAT IN (75) AND HINW_ZUST IS not NULL AND ART_EING != 'MAN' AND NR_AUF NOT IN ('940587') and DATUM_BESTELL > '01-11-2020'
SELECT * FROM (SELECT DATUM_BESTELL FROM AUFTRAEGE WHERE  STAT IN (75)  AND HINW_ZUST IS  not NULL AND ART_EING != 'MAN' AND NR_AUF NOT IN ('940587')  and DATUM_BESTELL > '01-11-2020' ORDER BY DATUM_BESTELL ASC ) WHERE ROWNUM=1 --DT ULTIMO PED